extends: [ 'eslint:recommended', 'plugin:@typescript-eslint/recommended', "react-app" ]
parser: '@typescript-eslint/parser'
plugins: [ '@typescript-eslint' ]
root: true
rules:
    "@typescript-eslint/no-non-null-assertion": off
    "import/no-anonymous-default-export": off
