extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:react-hooks/recommended
parser: "@typescript-eslint/parser"
plugins: [ "@typescript-eslint" ]
root: true
rules:
    no-mixed-spaces-and-tabs: [ error, smart-tabs ]
    no-cond-assign: off
    import/no-anonymous-default-export: off
    "@typescript-eslint/no-non-null-assertion": off
    "@typescript-eslint/no-unused-vars": warn
    "@typescript-eslint/no-explicit-any": warn
