name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Runtime
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Build
        run: deno task build
        env:
          BASE_URL: ${{ vars.BASE_URL }}

      - name: Create subpages
        run: |
          mkdir dist/add dist/multiply dist/convert
          cp dist/index.html dist/add
          cp dist/index.html dist/multiply
          cp dist/index.html dist/convert

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
            path: './dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
